name = "Fortran-Data-Compression"
version = "1.0.0"
author = "Adam K. Sokół, Wesley Cota"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
